apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- components/basic-python/base
- components/java-springboot-sample/base
- components/nodejs-sample/base
kind: Kustomization
resources:
- common-storage-pvc.yaml
